[package]
name = "home_calc"
version = "0.1.0"
authors = ["Cl√©ment Bizeau <clement.bizeau4@gmail.com>"]

[dependencies]
clap = "2.32.0"
prettytable-rs = "0.7.0"

[dev-dependencies]
float-cmp = "0.4.0"
